Lesson 1, part 1 (partially)
tritonJS826/trit-school-1 pull request #1
Opened 2021-09-15 10:42 UTC by Ekaterina1994

Created index.html. Added style.css. Added google.fonts. Added text, photo, link.

2021-09-15 11:17 UTC, tritonJS826 reviewed
Ok, not bad, but few pieces of advise yet: 
1. Don't use Russian language in your cv. Train yourself, use English.
2. Some western servers can't read Russians. Use English for files name.
3. Don't use spaces in file name. Sometimes u want to get access to them for example from console and it is hard to use special escaping symbols with spaces.

2021-09-15 11:17 UTC, tritonJS826 commented on code/FirstProgect/assets/css/style.css
> +
If you want to devide reset.css styles and your own styles, it's better to use comments thanempty lines

2021-09-15 11:17 UTC, tritonJS826 commented on code/FirstProgect/assets/css/style.css
> +p {
Don't add special styles to take. Use classes instead. What would u do if u will decide to use <p> with another styles?)

2021-09-15 11:17 UTC, tritonJS826 commented on code/FirstProgect/assets/css/style.css
> +.page>img {
"page" is too abstract name. I don't understand why do u need this syntax. U can use just image class name.

2021-09-15 12:28 UTC, tritonJS826 commented on code/FirstProgect/index.html
> +        <div class="Skills">
don't use UpperCase in your css files. It's better to use snake-case.

2021-09-15 12:29 UTC, tritonJS826 commented on code/FirstProgect/index.html
> +        <div class="expierance">
add word checker to your IDE, it helps to avoid stupid mistakes) I use it everytime (english and russian)

2021-09-15 12:31 UTC, tritonJS826 commented on code/FirstProgect/index.html
> +        <div class="Extra">
Where do u use this class names? I don't found them in your .css file. Remove unnecessary class definitions and etc.

2021-09-21 12:32 UTC, Ekaterina1994 commented on code/FirstProgect/assets/css/style.css
> +
Added comments line to divide reset and my styles.

2021-09-21 12:35 UTC, Ekaterina1994 commented on code/FirstProgect/assets/css/style.css
> +p {
Gave classes to tags h1 and h2.

2021-09-21 12:42 UTC, Ekaterina1994 commented on code/FirstProgect/assets/css/style.css
> +.page>img {
Changed class's name 'page' to 'mySite'. Maybe its wrong but dk which title would be better.

2021-09-21 12:44 UTC, Ekaterina1994 commented on code/FirstProgect/assets/css/style.css
> +.page>img {
I should use psevdoclass :before because if i don't use then opacity don't work or work on all info but I need that it work only on background picture.

2021-09-21 12:45 UTC, Ekaterina1994 commented on code/FirstProgect/index.html
> +        <div class="Skills">
Done.

2021-09-21 13:16 UTC, Ekaterina1994 commented on code/FirstProgect/index.html
> +        <div class="Extra">
Added classes to .css.

2021-09-21 15:25 UTC, tritonJS826 requested changes

2021-09-21 15:25 UTC, tritonJS826 commented on code/FirstProgect/assets/css/style.css
> +
I don't see the comments on these lines. Where is COMMENT?

2021-09-21 15:25 UTC, tritonJS826 commented on code/FirstProgect/assets/css/style.css
> +.page>img {
bette to use something like "Main block", "Content block" etc.

2021-09-21 23:17 UTC, Ekaterina1994 commented on code/FirstProgect/assets/css/style.css
> +
Comments are on the top of the file.

2021-09-22 20:52 UTC, tritonJS826 reviewed
Merge into master after fixing all bugs

2021-09-22 20:52 UTC, tritonJS826 commented on code/FirstProgect/assets/css/style.css
> +
i mean dividing reset styles and your own styles. Divider can't placed at the top)

2021-09-23 12:05 UTC, Ekaterina1994 commented on code/FirstProgect/assets/css/style.css
> +
I don't understand. There are to comments. One starts reset styles and second starts new style.

2021-09-23 12:07 UTC, Ekaterina1994 commented on code/FirstProgect/assets/css/style.css
> +.page>img {
Renamed.

2021-09-23 16:00 UTC, merged